sql:
  tables:
    - geonames
    - country_info
    - geo_info

spark:
  output: output/
  geonames:
    data: data/geonames.txt
    cols:
      - geoname_id
      - name
      - asciiname
      - alternatenames
      - latitude
      - longitude
      - feature_class
      - feature_code
      - country_code
      - cc2
      - admin1_code
      - admin2_code
      - admin3_code
      - admin4_code
      - population
      - elevation
      - dem
      - timezone
      - modification_date
    final_cols:
      - geoname_id
      - asciiname
      - latitude
      - longitude
      - feature_class
      - feature_code
      - country_code
      - dem
      - timezone
  country_info:
    data: data/country_info.csv
    cols:
      - ISO
      - ISO3
      - ISO-numeric
      - fips
      - country
      - capital
      - area_sq_km
      - population
      - continent
      - tld
      - currency_code
      - currency_name
      - phone
      - postal_code_format
      - postal_code_regex
      - languages
      - geonameid
      - neighbours
      - equivalent_fips_code
    final_cols:
      - ISO
      - fips
      - country
      - capital
      - area_sq_km
      - population
      - tld
      - currency_name
      - phone
      - languages
      - geonameid
      - neighbours
  geo_info:
    final_cols:
      - geoname_id
      - asciiname
      - latitude
      - longitude
      - feature_class
      - country
      - country_code
      - neighbours